TestWeb/Models/Container.cs
using System.Text.RegularExpressions;

namespace TestWeb.Models
{
    public class Container
    {
        
        public int ContainerID { get; set; }

        public string Client { get; set; }

        public string BillOfLading { get; set; }

        private string _containerIdentity;

        public string ContainerIdentity
        {
            get { return _containerIdentity; }
            set
            {
                if (IsValidContainerIdentity(value))
                    _containerIdentity = value;
                else
                    throw new ArgumentException("Invalid Container Identity format. It must be 4 letters followed by 7 numbers.");
            }
        }

        public string ContainerType { get; set; }

        public string ContainerDimension { get; set; }

        public bool Status { get; set; }

        public bool Comex { get; set; }

        private bool IsValidContainerIdentity(string identity)
        {
            return Regex.IsMatch(identity, @"^[A-Za-z]{4}\d{7}$");
        }
    }
}

TestWeb/Models/ErrorViewModel.cs
namespace TestWeb.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

TestWeb/Models/LoginPage.cs
namespace TestWeb.Models
{
    public class LoginPage
    {
        public int Id { get; set; }
        public string LoginName { get; set; } = string.Empty;
        public string Password { get; set; }
        public string PhoneNumber { get; set; }
        public string Email { get; set; }
    }
}

TestWeb/Models/Movimentation.cs
        
using System.ComponentModel.DataAnnotations;

namespace TestWeb.Models
{
    public class Movimentation
    {
        public int MovimentationID { get; set; }

        
        public MovimentationType Type { get; set; }

        
        public DateTime StartTime { get; set; }

      
        public DateTime EndTime { get; set; }

    }
}

TestWeb/Models/MovimentationType.cs
namespace TestWeb.Models
{
    public enum MovimentationType
    {
        GateIn,
        Reception,
        Scanner,
        Inspection,
        Discharge,
        Stacking,
        Weighing,
        Loading,
        Unloading,
        Transfer,
        Repair,
        Customs,
        GateOut
    }
}

TestWeb/Controllers/ContainerController.cs
using Microsoft.AspNetCore.Mvc;

namespace TestWeb.Controllers
{
    public class ContainerController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

TestWeb/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using TestWeb.Models;

namespace TestWeb.Controllers
{
    public class HomeController : Controller
    {
        
        public IActionResult Index()
        {
            return View();
        }

        

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

TestWeb/Controllers/LoginPageController.cs
using Microsoft.AspNetCore.Mvc;

namespace TestWeb.Controllers
{
    public class LoginPageController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

TestWeb/Controllers/MovimentationController.cs
using Microsoft.AspNetCore.Mvc;

namespace TestWeb.Controllers
{
    public class MovimentationController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

TestWeb/Views/Container/Index.cshtml
<form>
    <div class="form-group">
        <label for="ContainerId">ContainerId</label>
        <input type="text" class="form-control" id="containerid" placeholder="ContainerId">
    </div>

    <div class="form-group">
        <label for="Client">Client</label>
        <input type="text" class="form-control" id="client" placeholder="Client">
    </div>

    <div class="form-group">
        <label for="BillOfLading">Bill of Lading</label>
        <input type="text" class="form-control" id="billoflading" placeholder="Bill of Lading">
    </div>

    <div class="form-group">
        <label for="ContainerId">Container Identity</label>
        <input type="text" class="form-control" id="containeridentity" placeholder="Container Identity">
    </div>


    <div class="form-group">
        <label for="ContainerType">Container Type</label>
        <select class="form-control" id="Container Type">
            <option>Standard</option>
            <option>Reefer</option>
            <option>High Cube</option>
            <option>Open Top</option>
            <option>Flat Rack</option>
            <option>Tank</option>
            <option>Ventilado</option>
            <option>Open Side</option>
            <option>Platform</option>
            <option>Isothermal</option>
            <option>Half-Height</option>
        </select>
    </div>
    <div class="form-group">
        <label for="ContainerDimension">Container Dimension</label>
        <select multiple class="form-control" id="Container Dimension">
            <option>20</option>
            <option>40</option>            
        </select>
    </div>

    <div class="form-group">
        <label for="Status">Status</label>
        <input type="text" class="form-control" id="containerid" placeholder="Status">
    </div>

    <div class="form-group">
        <label for="Comex">Comex Operation</label>
        <input type="text" class="form-control" id="Comex" placeholder="Comex Operation">
    </div>

    <div class="form-group">
        <label for="Obs">Observations</label>
        <textarea class="form-control" id="observations" rows="10"></textarea>
    </div>
</form>
<button type="submit" form="container" value="Submit">Submit</button>

TestWeb/Views/Home/Index.cshtml
<h1>View Index</h1>

TestWeb/Views/LoginPage/Index.cshtml
<h2>Login Page</h2>


<partial name="_LoginPage" />

TestWeb/Views/LoginPage/LoginPage.cshtml
<h2>Login Page</h2>


<partial name="_LoginPage" />

TestWeb/Views/Movimentation/Index.cshtml
<h2>Gerenciamento de Movimentação de Carga</h2>


<partial name="_Movimentation" />

TestWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TestWeb</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TestWeb.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TestWeb</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>  
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="LoginPage" >Login Page</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Container" >Container</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Movimentation" >Movimentation</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - TestWeb - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

TestWeb/Views/Shared/_LoginPage.cshtml
<form>
    <div class="mb-3">
        <label for="loginname" class="form-label">Login Name</label>
        <input type="text" class="form-control" id="loginname">
    </div>

    <div class="mb-3">
        <label for="email" class="form-label">Email address</label>
        <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
        <div id="emailHelp" class="form-text">We'll never share your email with anyone else.</div>
    </div>

    <div class="mb-3">
        <label for="exampleInputPassword1" class="form-label">Password</label>
        <input type="password" class="form-control" id="exampleInputPassword1">
    </div>
    
    <button type="submit" class="btn btn-primary">Submit</button>
</form>

TestWeb/Views/Shared/_Movimentation.cshtml
<form>
    <div class="form-group">
        <label for="MovimentationId">MovimentationId</label>
        <input class="form-control" id="movimentationid" placeholder="MovimentationId">
    </div>
    <div class="form-group">
        <label for="movimentationtype">Movimentation Type</label>
        <select class="form-control" id="MovimentationType">
            <option>GateIn</option>
            <option>Reception</option>
            <option>Scanner</option>
            <option>Inspetion</option>
            <option>Discharge</option>
            <option>Stacking</option>
            <option>Weighing</option>
            <option>Loading on Board</option>
            <option>Unloading from Board</option>
            <option>Transfer</option>
            <option>Repair</option>
            <option>Customs</option>
            <option>GateOut</option>
        </select>
    </div>
    <div class="form-group">
        <label for="starttime">Start Date</label>
        <input type="datetime-local" class="form-control" id="startime" placeholder="Start Time">
    </div>

    <div class="form-group">
        <label for="endtime">End Date</label>
        <input type="datetime-local" class="form-control" id="endtime" placeholder="End Time">
    </div>

    <div class="form-group">
        <label for="exampleFormControlTextarea1">Observations</label>
        <textarea class="form-control" id="observations" rows="10"></textarea>
    </div>
</form>

<button type="submit" form="form1" value="Submit">Submit</button>